#!/usr/bin/python
"""
Utility to query the default include PATH of gcc.

Supported options:

 -g, --gcc <path>       The binary to use as gcc (default: gcc)
 -h, --help             Display this help message
 -t, --type sys|normal  The type of include path to query (default: sys)

Depending on its argument, the script queries the default
(system) include path of gcc.
"""

# Copyright Abel Sinkovics (abel@sinkovics.hu)  2013.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

import sys
import subprocess
import getopt

def run(cmd):
  return subprocess.Popen(
    cmd, 
    stderr=subprocess.PIPE,
    stdout=subprocess.PIPE,
    stdin=subprocess.PIPE
  ).communicate(input='')

def get_standard_gcc_includes(gcc):
  cc1plus = run((gcc, '-print-prog-name=cc1plus'))[0].strip()
  includes = []
  sysincludes = []
  current = None
  for l in run((cc1plus, '-v'))[1].split('\n'):
    retry = True
    while retry:
      retry = False
      if current == None:
        if l.startswith('#include "'):
          current = includes
        elif l.startswith('#include <'):
          current = sysincludes
      else:
        if l.startswith(' '):
          current.append(l.strip())
        else:
          current = None
          retry = True
  return (includes, sysincludes)

def main():
  try:
    opts, args = getopt.getopt(sys.argv[1:], 'ht:g:', ['help', 'type=', 'gcc='])
  except getopt.error, msg:
    print msg
    print "Getting help: --help"
    sys.exit(1)

  type = 'sys'
  gcc = 'gcc'

  for o, a in opts:
    if o in ('-t', '--type'):
      if a in ('sys', 'normal'):
        type = a
      else:
        print 'Invalid type: %s' % (a)
        sys.exit(1)
    elif o in('-h', '--help'):
      print __doc__
      sys.exit(0)
    elif o in('-g', '--gcc'):
      gcc = a
  
  (normal, system) = get_standard_gcc_includes(gcc)
  if type == 'sys':
    paths = system
  else:
    paths = normal
  print '\n'.join([', "%s"' % s for s in paths])
  print ''

if __name__ == '__main__':
  main()


