#!/usr/bin/python

# Copyright Abel Sinkovics (abel@sinkovics.hu)  2013.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

import re
import sys
import optparse

def anchor(c, toc_type):
  if c == ' ':
    return '-'
  elif c == '.':
    if toc_type == 'pandoc_html':
      return '.'
    else:
      return ''
  elif c in [':', '`']:
    return ''
  else:
    return c.lower()

def index_anchor(a, n):
  return '%s-%d' % (a, n)

class Header:
  def __init__(self, s, prev_anchors, toc_type):
    [pre, title] = s.split(' ', 1)
    self.depth = len(pre) - 1
    self.title = title.strip()
    self.anchor = ''.join([anchor(c, toc_type) for c in self.title])
    if self.anchor in prev_anchors:
      i = 1
      while index_anchor(self.anchor, i) in prev_anchors:
        i = i + 1
      self.anchor = index_anchor(self.anchor, i)

  def toc_line(self, indent):
    return \
      '%s- [%s](#%s)' % ('    ' * (self.depth+indent), self.title, self.anchor)

def is_header(s):
  return re.compile('^[#]+ ').search(s)

def collect_headers(doc, toc_type):
  header_lines = [s for s in doc if is_header(s)]
  headers = []
  anchors = []
  for s in header_lines:
    h = Header(s, anchors, toc_type)
    headers.append(h)
    anchors.append(h.anchor)
  return headers

def generate_toc(headers, toc_title):
  return \
    '\n'.join( \
      [h.toc_line(-1) for h in headers if h.depth > 0 and h.title != toc_title]\
    ) + '\n'

def generate_doc(f, doc, toc_title, toc_type):
  in_toc = False
  for s in doc:
    if in_toc:
      if is_header(s):
        f.write(s)
        in_toc = False
    else:
      if is_header(s) and Header(s, [], toc_type).title == toc_title:
        in_toc = True
        if toc_type != 'none':
          f.write(s + '\n')
          f.write(generate_toc(collect_headers(doc, toc_type), toc_title))
          f.write('\n')
      else:
        f.write(s)

def main():
  accepted_types = ['github', 'pandoc_html', 'none']
  parser = optparse.OptionParser()
  parser.add_option(
    '-i', '--input',
    action='store',
    dest='input',
    help='The file to process'
  )
  parser.add_option(
    '-o', '--output',
    action='store',
    dest='output',
    help='The file to write the result into. It defaults to the input file. To write output to stdout use: -'
  )
  parser.add_option(
    '-t', '--type',
    action='store',
    dest='type',
    default='github',
    help='Type of TOC. Possible values: %s. Default: %s'
      % (', '.join(accepted_types), 'github')
  )
  
  (options, args) = parser.parse_args()
  if options.output == None:
    options.output = options.input

  if options.input == None:
    parser.error('No input file specified')
  elif not options.type in accepted_types:
    parser.error('Invalid type: %s' % (options.type))
  else:
    toc_title = 'Table of contents'
    doc = open(options.input, 'r').readlines()
    if options.output == '-':
      f = sys.stdout
    else:
      f = open(options.output, 'w')
    generate_doc(f, doc, toc_title, options.type)

if __name__ == '__main__':
  main()

