#!/usr/bin/python

# Copyright Abel Sinkovics (abel@sinkovics.hu)  2014.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

import re
import sys
import optparse

def do_replace(f, doc, replace_with, marker):
  in_text_to_replace = False
  for s in doc:
    if s.find(marker) != -1:
      f.write(s)
      in_text_to_replace = not in_text_to_replace
      if in_text_to_replace:
        f.write(''.join(replace_with))
        f.write('\n')
    elif not in_text_to_replace:
      f.write(s)

def main():
  parser = optparse.OptionParser()
  parser.add_option(
    '-i', '--input',
    action='store',
    dest='input',
    help='The file to process'
  )
  parser.add_option(
    '-o', '--output',
    action='store',
    dest='output',
    help='The file to write the result into. It defaults to the input file. To write output to stdout use: -'
  )
  parser.add_option(
    '-r', '--replace_with',
    action='store',
    dest='replace_with',
    help='The file containing the part to place into <input>'
  )
  parser.add_option(
    '-m', '--marker',
    action='store',
    dest='marker',
    help='The marker to search for'
  )

  (options, args) = parser.parse_args()
  if options.output == None:
    options.output = options.input

  if options.input == None:
    parser.error('No input file specified')
  elif options.replace_with == None:
    parser.error('No file to replace with specified')
  else:
    doc = open(options.input, 'r').readlines()
    if options.output == '-':
      f = sys.stdout
    else:
      f = open(options.output, 'w')
    if options.replace_with == '-':
      r = sys.stdin.readlines()
    else:
      r = open(options.replace_with, 'r').readlines()
    do_replace(f, doc, r, options.marker)

if __name__ == '__main__':
  main()

